services:
  - type: web
    name: agentic-ai-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "reflex run --env prod --app app.app:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agentic-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_PUBLIC_URL
        sync: false

databases:
  - name: agentic-db
    databaseName: agentic_db
    plan: free 