services:
  - type: web
    name: claims-management-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: reflex run --env prod --app app.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: GOOGLE_CLOUD_PROJECT_ID
        sync: false
      - key: GOOGLE_CLOUD_BUCKET_NAME
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
      - key: GMAIL_CREDENTIALS_JSON
        sync: false
      - key: GMAIL_TOKEN_JSON
        sync: false
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: claims-db
    databaseName: claims_db
    user: claims_user
    plan: free 