services:
  - type: web
    name: claims-management-system
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      reflex init
      reflex export
    startCommand: "reflex run --env prod --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: claims-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_CLOUD_PROJECT_ID
        value: velvety-glyph-464401-v6
      - key: GOOGLE_CLOUD_STORAGE_BUCKET
        value: claims-documents-zurich-ai
      - key: GOOGLE_CLOUD_STORAGE_FOLDER
        value: documentos
      - key: GMAIL_CREDENTIALS_JSON
        sync: false
      - key: GMAIL_TOKEN_JSON
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FROM_EMAIL
        value: gerardo_mayel_fernandez_alamilla@chiefdataaiofficer.com
      - key: GMAIL_USER_EMAIL
        value: gerardo_mayel_fernandez_alamilla@chiefdataaiofficer.com
      - key: REFLEX_LOG_LEVEL
        value: debug


databases:
  - name: claims-db
    databaseName: claims_ropj
    user: agent 