services:
  # Backend API Service
  - type: web
    name: zurich-claims-api
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: cd backend && PYTHONPATH=/opt/render/project/src/backend python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      # Database Configuration
      - key: DATABASE_URL
        value: postgresql://agent:DoyP8c9r4AV7Y2x12OyEJub8si46wavT@dpg-d1gb61bipnbc73agtmm0-a.oregon-postgres.render.com/claims_ropj
      
      # Google Cloud Storage Configuration
      - key: GOOGLE_CLOUD_STORAGE_BUCKET
        value: claims-documents-zurich-ai
      - key: GOOGLE_CLOUD_PROJECT_ID
        value: velvety-glyph-464401-v6
      - key: GOOGLE_CLOUD_STORAGE_FOLDER
        value: documentos
      
      # Application Configuration
      - key: ENVIRONMENT
        value: production
      - key: FROM_EMAIL
        value: gerardo_mayel_fernandez_alamilla@chiefdataaiofficer.com
      - key: GMAIL_USER_EMAIL
        value: gerardo_mayel_fernandez_alamilla@chiefdataaiofficer.com
      - key: LOGLEVEL
        value: info
      
      # Domain Configuration
      - key: DOMAIN_NAME
        value: chiefdataaiofficer.com
      - key: WEBHOOK_EMAIL
        value: prueba@send.chiefdataaiofficer.com
      
      # Security Configuration
      - key: SECRET_KEY
        generateValue: true

  # Frontend Static Site
  - type: web
    name: zurich-claims-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://zurich-claims-api.onrender.com

databases:
  - name: claims-db
    databaseName: claims_ropj
    user: agent 