services:
  # Backend API Service
  - type: web
    name: zurich-claims-api
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GMAIL_CREDENTIALS_FILE
        sync: false
      - key: GOOGLE_CLOUD_STORAGE_BUCKET
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  # Frontend Static Site
  - type: web
    name: zurich-claims-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: claims-db
    databaseName: claims_ropj
    user: agent 